// Generated by CoffeeScript 1.9.3
(function() {
  require('../src/string');

  describe('strings', function() {
    it('sees if starts with', function() {
      var str;
      str = "tom s";
      return expect(str.startsWith("tom ")).toBe(true);
    });
    it('can check contains string', function() {
      var str;
      str = "tom s";
      expect(str.contains("to ")).toBe(false);
      return expect(str.contains("om ")).toBe(true);
    });
    it('can check if valid email', function() {
      var invalid1, invalid2, invalid3, invalid4, valid;
      valid = "shachamtom@gmail.com";
      invalid1 = "blah";
      invalid2 = "blah@";
      invalid3 = "blah@com";
      invalid4 = "@com";
      expect(valid.isValidEmail()).toBe(true);
      expect(invalid1.isValidEmail()).toBe(false);
      expect(invalid2.isValidEmail()).toBe(false);
      expect(invalid3.isValidEmail()).toBe(false);
      return expect(invalid4.isValidEmail()).toBe(false);
    });
    it('reverses strings', function() {
      var str;
      str = "tom s";
      return expect(str.reverse()).toEqual("s mot");
    });
    return it('pops last letter off', function() {
      var str;
      str = "tom s";
      return expect(str.pop()).toEqual("tom ");
    });
  });

}).call(this);
