// Generated by CoffeeScript 1.9.3
(function() {
  String.prototype.startsWith = function(str) {
    return this.indexOf(str) === 0;
  };

  String.prototype.contains = function(str) {
    return this.indexOf(str) !== -1;
  };

  String.prototype.isValidEmail = function() {
    var re;
    re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(this);
  };

  String.prototype.reverse = function() {
    return this.split('').reverse().join('');
  };

  String.prototype.pop = function() {
    return this.slice(0, -1);
  };

}).call(this);
